server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*

# USER SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# BOOKING SERVICE
spring.cloud.gateway.routes[1].id=booking-service
spring.cloud.gateway.routes[1].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/bookings/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthFilter

# FLIGHT INVENTORY SERVICE
spring.cloud.gateway.routes[2].id=flight-service
spring.cloud.gateway.routes[2].uri=lb://FLIGHT-INVENTORY-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/flights/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthFilter

# PAYMENT SERVICE
spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[3].filters[0]=JwtAuthFilter

# NOTIFICATION SERVICE
spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[4].filters[0]=JwtAuthFilter

# ADMIN SERVICE
spring.cloud.gateway.routes[5].id=admin-service
spring.cloud.gateway.routes[5].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.routes[5].filters[0]=JwtAuthFilter

# PAYMENT SERVICE
spring.cloud.gateway.routes[6].id=payment-service
spring.cloud.gateway.routes[6].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/payment/**
spring.cloud.gateway.routes[6].filters[0]=JwtAuthFilter

# CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*